<?php

/**
 * @file
 * Contains legal_repos.module.
 */

use \Drupal\field\Entity\FieldConfig;
use Drupal\legal_repos\Entity\AdaCaseNode;
use Drupal\legal_repos\Entity\ConsentDecreeNode;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function legal_repos_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['title_vii_consent_decree'])) {
    $bundles['node']['title_vii_consent_decree']['class'] = ConsentDecreeNode::class;
  }
  if (isset($bundles['node']['ada_case'])) {
    $bundles['node']['ada_case']['class'] = AdaCaseNode::class;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function legal_repos_entity_type_alter(array &$entity_types) {
  $entity_types['node']->addConstraint('UniqueCaseNumberVersion');
}

/**
 * Implements hook_entity_prepare_view().
 *
 * Set display-only default values for consent decree and ADA case nodes.
 */
function legal_repos_entity_prepare_view($entity_type_id, array $entities, array $displays, $view_mode) {
  if ($entity_type_id !== 'node') {
    return;
  }

  if ($view_mode !== 'full') {
    return;
  }

  /** @var \Drupal\Core\Entity\ContentEntityInterface $node */
  foreach ($entities as $node) {
    if (!in_array($node->bundle(), ['title_vii_consent_decree', 'ada_case'])) {
      return;
    }

    /** @var \Drupal\Core\Field\FieldItemList $field */
    foreach ($node->getFields() as $field_name => $field) {
      /** @var \Drupal\Core\Field\BaseFieldDefinition $field_definition */
      $field_definition = $field->getFieldDefinition();

      // This should match both `text_long` and `string` user-defined fields,
      // but not base fields.
      if ($field_definition instanceof FieldConfig && in_array($field_definition->getType(), ['text_long', 'string']) && $field->isEmpty()) {
        $node->set($field_name, t('[none specified]'));
      }
    }
  }
}
