<?php

/**
 * @file
 * Contains legal_repos.module.
 */

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use \Drupal\field\Entity\FieldConfig;
use Drupal\legal_repos\Entity\AdaCaseNode;
use Drupal\legal_repos\Entity\ConsentDecreeNode;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function legal_repos_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['title_vii_consent_decree'])) {
    $bundles['node']['title_vii_consent_decree']['class'] = ConsentDecreeNode::class;
  }
  if (isset($bundles['node']['ada_case'])) {
    $bundles['node']['ada_case']['class'] = AdaCaseNode::class;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function legal_repos_entity_type_alter(array &$entity_types) {
  $entity_types['node']->addConstraint('UniqueCaseNumberVersion');
}

/**
 * Implements hook_entity_prepare_view().
 *
 * Set display-only default values for consent decree and ADA case nodes.
 */
function legal_repos_entity_prepare_view($entity_type_id, array $entities, array $displays, $view_mode) {
  if ($entity_type_id !== 'node') {
    return;
  }

  if ($view_mode !== 'full') {
    return;
  }

  /** @var \Drupal\Core\Entity\ContentEntityInterface $node */
  foreach ($entities as $node) {
    if (!in_array($node->bundle(), ['title_vii_consent_decree', 'ada_case'])) {
      return;
    }

    /** @var \Drupal\Core\Field\FieldItemList $field */
    foreach ($node->getFields() as $field_name => $field) {
      /** @var \Drupal\Core\Field\BaseFieldDefinition $field_definition */
      $field_definition = $field->getFieldDefinition();

      // This should match both `text_long` and `string` user-defined fields,
      // but not base fields.
      if ($field_definition instanceof FieldConfig && in_array($field_definition->getType(), ['text_long', 'string']) && $field->isEmpty()) {
        $node->set($field_name, t('[none specified]'));
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function legal_repos_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['saml_login'] = [
    '#type' => 'link',
    '#url' => Url::fromRoute('samlauth.saml_controller_login'),
    '#title' => t('NetID Login'),
    '#weight' => -2,
    '#attributes' => [
      'class' => 'cu-button'
    ],
    '#attached' => [
      'library' => [
        'union_organizer/button'
      ]
    ]
  ];

  $form['drupal_login_container_open'] = [
    '#markup' => '<details><summary>' . t('No Cornell NetID?') . '</summary>',
    '#weight' => -1
  ];

  $form['drupal_login_container_close'] = [
    '#markup' => '</details><p></p>',
    '#weight' => 100
  ];
}

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
function legal_repos_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, $form_mode, $form, FormStateInterface $form_state) {
  $element = [];

  // Add a 'Disabled' checkbox to the settings form for 'number' field
  // formatters.
  if ($plugin->getPluginId() === 'number') {
    $element['disabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Disabled'),
      '#description' => t('Prevent the field value from being modified.'),
      '#default_value' => $plugin->getThirdPartySetting('legal_repos', 'disabled'),
    ];
  }

  return $element;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function legal_repos_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  if ($context['widget']->getThirdPartySetting('legal_repos', 'disabled')) {
    $element['#disabled'] = TRUE;
  }
}
